### ISSUE TITLE
Different showReference-Settings possible?

### ISSUE THREAD

**Issue by schlundus** [BrainMaxx/tslens#12]
Is it possible (i know ... currently not) to turn on/off reference depending on the type?

My Setting:
I've also activated normal VSCode CodeLens which already shows references for some stuff..
Your extension also shows references but also it shows some more references ..... like variables ...

As a result i have some duplicate information displayed.....
If i disable the references in your extension, the reference-information for the variables is also lost... which is bad

I've attached a screenshot.. .the yellowones are duplicates, the red ones are cool

![image](https://user-images.githubusercontent.com/17083185/41897889-ddb969a0-7928-11e8-8671-11edde9542ed.png)

So my question is now, can you provide different on/off settings for references which are already shown in standard Vscode

**Comment by BrainMaxx** [comment]
Hard to say, I guess I cant do anything with another extensions, but I will think about extending current settings

**Comment by BrainMaxx** [comment]
@schlundus I added an option **tslens.referencesTypes**  which is an array of numbers from [link](https://github.com/Microsoft/vscode/blob/0532c31e4c1eee343aec19b55672c2d79b51f6f4/src/vs/editor/common/modes.ts#L585) By default all 25 items included, so you could choose just some of them

**Comment by schlundus** [comment]
I've tried it with my example, but as soon as i deactivate for example "4" in the array,.. 
it crashes with some exeception and nothing is hidden
--schnipp--
  ERR Cannot read property 'getNamespaces' of undefined: TypeError: Cannot read property 'getNamespaces' of undefined
    at TSCodeLensProvider.<anonymous> (C:\Users\a.morsing\.vscode\extensions\maxgotovkin.tslens-1.2.5\out\src\providers\TSCodeLensProvider.js:127:40)
    at Generator.next (<anonymous>)
    at 
--schnapp--
or this one
--schnipp--
 ERR Cannot read property 'getImportDeclarations' of undefined: TypeError: Cannot read property 'getImportDeclarations' of undefined
    at TSCodeLensProvider.<anonymous> (C:\Users\a.morsing\.vscode\extensions\maxgotovkin.tslens-1.2.5\out\src\providers\TSCodeLensProvider.js:117:29)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\a.morsing\.vscode\extensions\maxgotovkin.tslens-1.2.5\out\src\providers\TSCodeLensProvider.js:4:58)
    at <anonymous>
--schnapp--

JSON stringified exception
--schnipp--
"{"exception":null,"error":[null,null,null,null,null,null,null,null,[null,null,{"name":"TypeError","message":"Cannot read property 'getNamespaces' of undefined"}],[null,null,{"name":"TypeError","message":"Cannot read property 'getNamespaces' of undefined"}],[null,null,{"name":"TypeError","message":"Cannot read property 'getNamespaces' of undefined"}]],"promise":{"_oncancel":null,"_nextState":null,"_state":{"name":"error","done":null,"then":null},"_listeners":null,"_value":[null,null,null,null,null,null,null,null,[null,null,{"name":"TypeError","message":"Cannot read property 'getNamespaces' of undefined"}],[null,null,{"name":"TypeError","message":"Cannot read property 'getNamespaces' of undefined"}],[null,null,{"name":"TypeError","message":"Cannot read property 'getNamespaces' of undefined"}]],"_isException":false,"_errorId":95},"id":95}"
--schnapp--

Maybe that helps..

**Comment by BrainMaxx** [comment]
@schlundus I could not reproduce the bug, but I added some additionl checks to not let the extension to crash

**Comment by schlundus** [comment]
Yeah, it works much better now... some small glitches... 

This is my setting
--schnipp--
"tslens.referencesTypes": [
    0,
    1,
    // 2, // namespace
    3,
    // 4, // classes
    // 5, // method
    // 6, // property
    7,
    //8, // constructor
    9,
    // 10, // Interface
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25
  ],
--schnapp---

Namespace Ref still shown
constructor Ref still shown

![image](https://user-images.githubusercontent.com/17083185/41969815-f1ffa10a-7a08-11e8-9b6e-cf7efef098e6.png)

The red one is OK...

**Comment by BrainMaxx** [comment]
@schlundus  marked red - this is 'variable' - code 12, for some reason namespace has kind of 1 - 'module' but not 'namespace', maybe some bug of VSCode...

**Comment by schlundus** [comment]
Ah ok... good to know. Thanks for your efforts
